# Generated by Django 5.1.2 on 2024-12-10 21:33

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('fifty_fifty', 9), ('side_by_side', 10), ('full_screen_image_with_text_over', 14)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Relative URL to page, e.g. /about-us/meet-the-team'}), 5: ('wagtail.blocks.StructBlock', [[('display_text', 3), ('path', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'max_num': 1, 'min_num': 0}), 7: ('wagtail.blocks.StructBlock', [[('show_button', 2)]], {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('aqua', 'Aqua'), ('black', 'Black'), ('charbrown', 'Charcoal Brown'), ('g2', 'Gen2'), ('g2blk', 'Gen2 Black'), ('racing', 'Racing'), ('seventycx', 'Seventy CX'), ('taskabackgroundgrey', 'TASKA Background Grey'), ('taskablack', 'TASKA Black'), ('taskablue', 'TASKA Blue'), ('taskacharcoal', 'TASKA Charcoal'), ('taskacoolgrey', 'TASKA Cool Grey'), ('taskadarkblue', 'TASKA Dark Blue'), ('taskagrey', 'TASKA Grey'), ('taskapink', 'TASKA Pink'), ('taskared', 'TASKA RED'), ('taskaultralightgrey', 'TASKA Ultralight Grey'), ('taskawheat', 'TASKA Wheat'), ('white', 'White')]}), 9: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('image_on_left', 2), ('video_overlay', 2), ('button', 6), ('scroll_button', 7), ('bg_color', 8), ('text_color', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('button', 5), ('scroll_button', 7), ('bg_color', 8), ('text_color', 8)]], {}), 11: ('wagtail.blocks.TextBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('title', 3), ('description', 11), ('image', 1), ('new', 2), ('button', 5), ('bg_color', 8)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('bg_color', 8), ('text_color', 8), ('fade_image', 2), ('show_button', 2), ('text_on_left', 2), ('button', 5), ('cards', 13)]], {})}, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hidden', models.BooleanField(default=False, help_text='Hide page from users.')),
                ('content', wagtail.fields.StreamField([('page_title', 2), ('display', 5), ('staff_grid', 9), ('fifty_fifty', 15), ('side_by_side', 16), ('full_screen_image_with_text_over', 20), ('privacy_policy', 21), ('downloads', 31), ('overflow_card_list', 34), ('frequently_asked_questions', 38)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('aqua', 'Aqua'), ('black', 'Black'), ('charbrown', 'Charcoal Brown'), ('g2', 'Gen2'), ('g2blk', 'Gen2 Black'), ('racing', 'Racing'), ('seventycx', 'Seventy CX'), ('taskabackgroundgrey', 'TASKA Background Grey'), ('taskablack', 'TASKA Black'), ('taskablue', 'TASKA Blue'), ('taskacharcoal', 'TASKA Charcoal'), ('taskacoolgrey', 'TASKA Cool Grey'), ('taskadarkblue', 'TASKA Dark Blue'), ('taskagrey', 'TASKA Grey'), ('taskapink', 'TASKA Pink'), ('taskared', 'TASKA RED'), ('taskaultralightgrey', 'TASKA Ultralight Grey'), ('taskawheat', 'TASKA Wheat'), ('white', 'White')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('text_color', 1), ('bg_color', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('columns', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 0), ('image', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('staff', 8)]], {}), 10: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 11: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Relative URL to page, e.g. /about-us/meet-the-team'}), 12: ('wagtail.blocks.StructBlock', [[('display_text', 0), ('path', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'max_num': 1, 'min_num': 0}), 14: ('wagtail.blocks.StructBlock', [[('show_button', 10)]], {}), 15: ('wagtail.blocks.StructBlock', [[('text', 3), ('image', 6), ('image_on_left', 10), ('video_overlay', 10), ('button', 13), ('scroll_button', 14), ('bg_color', 1), ('text_color', 1)]], {}), 16: ('wagtail.blocks.StructBlock', [[('text', 3), ('image', 6), ('button', 12), ('scroll_button', 14), ('bg_color', 1), ('text_color', 1)]], {}), 17: ('wagtail.blocks.TextBlock', (), {}), 18: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 17), ('image', 6), ('new', 10), ('button', 12), ('bg_color', 1)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.StructBlock', [[('text', 3), ('image', 6), ('bg_color', 1), ('text_color', 1), ('fade_image', 10), ('show_button', 10), ('text_on_left', 10), ('button', 12), ('cards', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[]], {}), 22: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('clinician', 'Clinicians'), ('user', 'Users')]}), 23: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 24: ('wagtail.blocks.StructBlock', [[('title', 0), ('category', 22), ('file', 23)]], {}), 25: ('wagtail.blocks.URLBlock', (), {}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('document', 'Document'), ('image', 'Image'), ('link', 'Link'), ('software', 'Software'), ('youtube', 'YouTube'), ('other', 'Other')]}), 27: ('wagtail.blocks.StructBlock', [[('title', 0), ('category', 22), ('file', 23), ('url', 25), ('file_type', 26)]], {}), 28: ('wagtail.blocks.StreamBlock', [[('file', 24), ('external_content', 27)]], {}), 29: ('wagtail.blocks.StructBlock', [[('title', 0), ('downloads', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {}), 31: ('wagtail.blocks.StructBlock', [[('categories', 30)]], {}), 32: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 17), ('image', 6), ('image_on_right', 10), ('image_pop_out', 10), ('bg_color', 1), ('text_color', 1)]], {}), 33: ('wagtail.blocks.ListBlock', (32,), {}), 34: ('wagtail.blocks.StructBlock', [[('title', 3), ('cards', 33), ('bg_color', 1), ('text_color', 1)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'required': False}), 36: ('wagtail.blocks.StructBlock', [[('title', 35), ('text', 3)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {}), 38: ('wagtail.blocks.StructBlock', [[('title', 0), ('entries', 37)]], {})}, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BottomNavigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nav_blocks', wagtail.fields.StreamField([('navigation_block', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 2)]], {})})),
                ('extra_links', wagtail.fields.StreamField([('page', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {})}, help_text='Extra links to display at bottom of page.', null=True)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Footer Navigation',
                'verbose_name_plural': 'Footer Navigation',
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_home_bottomnavigation')],
            },
        ),
        migrations.CreateModel(
            name='HeaderNavigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('central_nav', wagtail.fields.StreamField([('navigation_block', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 2)]], {})})),
                ('right_hand_nav', wagtail.fields.StreamField([('navigation_block', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 2)]], {})})),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Header Navigation',
                'verbose_name_plural': 'Header Navigation',
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_home_headernavigation')],
            },
        ),
    ]
