# Generated by Django 5.1.4 on 2024-12-11 01:51

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='content',
            field=wagtail.fields.StreamField([('page_title', 2), ('display', 5), ('staff_grid', 9), ('fifty_fifty', 15), ('side_by_side', 16), ('full_screen_image_with_text_over', 20), ('privacy_policy', 21), ('downloads', 31), ('overflow_card_list', 34), ('frequently_asked_questions', 38), ('select_display', 40)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('aqua', 'Aqua'), ('black', 'Black'), ('charbrown', 'Charcoal Brown'), ('g2', 'Gen2'), ('g2blk', 'Gen2 Black'), ('racing', 'Racing'), ('seventycx', 'Seventy CX'), ('taskabackgroundgrey', 'TASKA Background Grey'), ('taskablack', 'TASKA Black'), ('taskablue', 'TASKA Blue'), ('taskacharcoal', 'TASKA Charcoal'), ('taskacoolgrey', 'TASKA Cool Grey'), ('taskadarkblue', 'TASKA Dark Blue'), ('taskagrey', 'TASKA Grey'), ('taskapink', 'TASKA Pink'), ('taskared', 'TASKA RED'), ('taskaultralightgrey', 'TASKA Ultralight Grey'), ('taskawheat', 'TASKA Wheat'), ('white', 'White')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('text_color', 1), ('bg_color', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('columns', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 0), ('image', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('staff', 8)]], {}), 10: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 11: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Relative URL to page, e.g. /about-us/meet-the-team'}), 12: ('wagtail.blocks.StructBlock', [[('display_text', 0), ('path', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'max_num': 1, 'min_num': 0}), 14: ('wagtail.blocks.StructBlock', [[('show_button', 10)]], {}), 15: ('wagtail.blocks.StructBlock', [[('text', 3), ('image', 6), ('image_on_left', 10), ('video_overlay', 10), ('button', 13), ('scroll_button', 14), ('bg_color', 1), ('text_color', 1)]], {}), 16: ('wagtail.blocks.StructBlock', [[('text', 3), ('image', 6), ('button', 12), ('scroll_button', 14), ('bg_color', 1), ('text_color', 1)]], {}), 17: ('wagtail.blocks.TextBlock', (), {}), 18: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 17), ('image', 6), ('new', 10), ('button', 12), ('bg_color', 1)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.StructBlock', [[('text', 3), ('image', 6), ('bg_color', 1), ('text_color', 1), ('fade_image', 10), ('show_button', 10), ('text_on_left', 10), ('button', 12), ('cards', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[]], {}), 22: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('clinician', 'Clinicians'), ('user', 'Users')]}), 23: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 24: ('wagtail.blocks.StructBlock', [[('title', 0), ('category', 22), ('file', 23)]], {}), 25: ('wagtail.blocks.URLBlock', (), {}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('document', 'Document'), ('image', 'Image'), ('link', 'Link'), ('software', 'Software'), ('youtube', 'YouTube'), ('other', 'Other')]}), 27: ('wagtail.blocks.StructBlock', [[('title', 0), ('category', 22), ('file', 23), ('url', 25), ('file_type', 26)]], {}), 28: ('wagtail.blocks.StreamBlock', [[('file', 24), ('external_content', 27)]], {}), 29: ('wagtail.blocks.StructBlock', [[('title', 0), ('downloads', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {}), 31: ('wagtail.blocks.StructBlock', [[('categories', 30)]], {}), 32: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 17), ('image', 6), ('image_on_right', 10), ('image_pop_out', 10), ('bg_color', 1), ('text_color', 1)]], {}), 33: ('wagtail.blocks.ListBlock', (32,), {}), 34: ('wagtail.blocks.StructBlock', [[('title', 3), ('cards', 33), ('bg_color', 1), ('text_color', 1)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'required': False}), 36: ('wagtail.blocks.StructBlock', [[('title', 35), ('text', 3)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {}), 38: ('wagtail.blocks.StructBlock', [[('title', 0), ('entries', 37)]], {}), 39: ('wagtail.blocks.ListBlock', (5,), {}), 40: ('wagtail.blocks.StructBlock', [[('title', 0), ('entries', 39)]], {})}, null=True),
        ),
        migrations.CreateModel(
            name='StayInTouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content', wagtail.fields.RichTextField(blank=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
