# Generated by Django 5.1.4 on 2024-12-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_standardpage_content_stayintouch'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='add_bottom_padding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='add_bottom_padding',
            field=models.BooleanField(default=True),
        ),
    ]
