# Generated by Django 5.1.4 on 2024-12-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_homepage_charset_homepage_og_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='charset',
            field=models.CharField(default='utf-8', max_length=50),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='og_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='og_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='viewport',
            field=models.CharField(default='width=device-width, initial-scale=1', max_length=50),
        ),
    ]
