# Generated by Django 5.1.4 on 2024-12-31 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_blogpost_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='header',
        ),
    ]
