# Generated by Django 5.1.4 on 2024-12-31 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_blogpost_header'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
