# Generated by Django 5.1.4 on 2024-12-31 04:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
        ('website', '0011_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('charset', models.CharField(default='utf-8', max_length=50)),
                ('viewport', models.CharField(default='width=device-width, initial-scale=1', max_length=50)),
                ('og_title', models.CharField(blank=True, max_length=200, null=True)),
                ('og_description', models.CharField(blank=True, max_length=200, null=True)),
                ('header', wagtail.fields.StreamField([('page_header', 3)], block_lookup={0: ('wagtail.blocks.TextBlock', (), {'help_text': 'A quote to display on the left-hand side.', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Attribution for the quote.', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': ['title', 'Title and Image'], 'required': ('image', 'Only Image')}), 3: ('wagtail.blocks.StructBlock', [[('quote', 0), ('attribution', 1), ('display_option', 2)]], {})})),
                ('date', models.DateField(verbose_name='Post date')),
                ('content', wagtail.fields.StreamField([('text', 0), ('image', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
