name: Django CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - 5432:5432
      redis:
        image: redis:7.4-alpine
        ports:
          - 6379:6379
    env:
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_pass
      DB_HOST: localhost
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: website_django.settings.dev
      PYTHONUNBUFFERED: 1
      REDIS_CACHE: redis://localhost:6379
      RQ_REDIS_HOST: localhost
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Poetry
        run: pip install poetry
      - name: Set Poetry to use in-project virtualenv
        run: poetry config virtualenvs.in-project true
      - name: Cache Poetry virtualenv and cache
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install dependencies
        run: poetry install
      - name: Run migrations
        run: poetry run python manage.py migrate
      - name: Run tests
        run: poetry run pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Poetry
        run: pip install poetry
      - name: Set Poetry to use in-project virtualenv
        run: poetry config virtualenvs.in-project true
      - name: Cache Poetry virtualenv and cache
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install dependencies
        run: poetry install
      - name: Run ruff linter (check only)
        run: poetry run ruff check .
