# Generated by Django 5.1.4 on 2024-12-27 03:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_homepage_add_bottom_padding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('fifty_fifty', 9), ('home_page_cover', 10), ('side_by_side', 11), ('full_screen_image_with_text_over', 15), ('product_comparison', 18)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Relative URL to page, e.g. /about-us/meet-the-team'}), 5: ('wagtail.blocks.StructBlock', [[('display_text', 3), ('path', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'max_num': 1, 'min_num': 0}), 7: ('wagtail.blocks.StructBlock', [[('show_button', 2)]], {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('aqua', 'Aqua'), ('black', 'Black'), ('charbrown', 'Charcoal Brown'), ('g2', 'Gen2'), ('g2blk', 'Gen2 Black'), ('racing', 'Racing'), ('seventycx', 'Seventy CX'), ('taskabackgroundgrey', 'TASKA Background Grey'), ('taskablack', 'TASKA Black'), ('taskablue', 'TASKA Blue'), ('taskacharcoal', 'TASKA Charcoal'), ('taskacoolgrey', 'TASKA Cool Grey'), ('taskadarkblue', 'TASKA Dark Blue'), ('taskagrey', 'TASKA Grey'), ('taskapink', 'TASKA Pink'), ('taskared', 'TASKA RED'), ('taskaultralightgrey', 'TASKA Ultralight Grey'), ('taskawheat', 'TASKA Wheat'), ('white', 'White')]}), 9: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('image_on_left', 2), ('video_overlay', 2), ('button', 6), ('scroll_button', 7), ('bg_color', 8), ('text_color', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('bg_color', 8), ('text_color', 8), ('button', 5)]], {}), 11: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('button', 5), ('scroll_button', 7), ('bg_color', 8), ('text_color', 8)]], {}), 12: ('wagtail.blocks.TextBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 3), ('description', 12), ('image', 1), ('new', 2), ('button', 5), ('bg_color', 8)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('bg_color', 8), ('text_color', 8), ('fade_image', 2), ('show_button', 2), ('text_on_left', 2), ('button', 5), ('cards', 14)]], {}), 16: ('wagtail.blocks.PageChooserBlock', (), {}), 17: ('wagtail.blocks.ListBlock', (1,), {'max_num': 2}), 18: ('wagtail.blocks.StructBlock', [[('text', 0), ('link', 16), ('images', 17)]], {})}, null=True),
        ),
    ]
