# Generated by Django 5.1.4 on 2024-12-30 07:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
        ('website', '0007_alter_homepage_og_image_alter_standardpage_og_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogOverviewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('charset', models.CharField(default='utf-8', max_length=50)),
                ('viewport', models.CharField(default='width=device-width, initial-scale=1', max_length=50)),
                ('og_title', models.CharField(blank=True, max_length=200, null=True)),
                ('og_description', models.CharField(blank=True, max_length=200, null=True)),
                ('content', wagtail.fields.StreamField([('page_title', 2), ('fifty_fifty', 10)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('aqua', 'Aqua'), ('black', 'Black'), ('charbrown', 'Charcoal Brown'), ('g2', 'Gen2'), ('g2blk', 'Gen2 Black'), ('racing', 'Racing'), ('seventycx', 'Seventy CX'), ('taskabackgroundgrey', 'TASKA Background Grey'), ('taskablack', 'TASKA Black'), ('taskablue', 'TASKA Blue'), ('taskacharcoal', 'TASKA Charcoal'), ('taskacoolgrey', 'TASKA Cool Grey'), ('taskadarkblue', 'TASKA Dark Blue'), ('taskagrey', 'TASKA Grey'), ('taskapink', 'TASKA Pink'), ('taskared', 'TASKA RED'), ('taskaultralightgrey', 'TASKA Ultralight Grey'), ('taskawheat', 'TASKA Wheat'), ('white', 'White')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('text_color', 1), ('bg_color', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Relative URL to page, e.g. /about-us/meet-the-team'}), 7: ('wagtail.blocks.StructBlock', [[('display_text', 0), ('path', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'max_num': 1, 'min_num': 0}), 9: ('wagtail.blocks.StructBlock', [[('show_button', 5)]], {}), 10: ('wagtail.blocks.StructBlock', [[('text', 3), ('image', 4), ('image_on_left', 5), ('video_overlay', 5), ('button', 8), ('scroll_button', 9), ('bg_color', 1), ('text_color', 1)]], {})})),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('charset', models.CharField(default='utf-8', max_length=50)),
                ('viewport', models.CharField(default='width=device-width, initial-scale=1', max_length=50)),
                ('og_title', models.CharField(blank=True, max_length=200, null=True)),
                ('og_description', models.CharField(blank=True, max_length=200, null=True)),
                ('header', wagtail.fields.StreamField([('fifty_fifty', 9)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Relative URL to page, e.g. /about-us/meet-the-team'}), 5: ('wagtail.blocks.StructBlock', [[('display_text', 3), ('path', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'max_num': 1, 'min_num': 0}), 7: ('wagtail.blocks.StructBlock', [[('show_button', 2)]], {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('aqua', 'Aqua'), ('black', 'Black'), ('charbrown', 'Charcoal Brown'), ('g2', 'Gen2'), ('g2blk', 'Gen2 Black'), ('racing', 'Racing'), ('seventycx', 'Seventy CX'), ('taskabackgroundgrey', 'TASKA Background Grey'), ('taskablack', 'TASKA Black'), ('taskablue', 'TASKA Blue'), ('taskacharcoal', 'TASKA Charcoal'), ('taskacoolgrey', 'TASKA Cool Grey'), ('taskadarkblue', 'TASKA Dark Blue'), ('taskagrey', 'TASKA Grey'), ('taskapink', 'TASKA Pink'), ('taskared', 'TASKA RED'), ('taskaultralightgrey', 'TASKA Ultralight Grey'), ('taskawheat', 'TASKA Wheat'), ('white', 'White')]}), 9: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('image_on_left', 2), ('video_overlay', 2), ('button', 6), ('scroll_button', 7), ('bg_color', 8), ('text_color', 8)]], {})})),
                ('content', wagtail.fields.StreamField([('text', 0), ('image', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
