# Generated by Django 5.1.5 on 2025-01-19 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0012_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='header',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='header_options',
            field=models.IntegerField(choices=[(0, 'Title'), (1, 'Title and Image'), (2, 'Only Image')], default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='header_quote',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='header_quote_attribution',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
