# Generated by Django 5.1.6 on 2025-03-05 04:19

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_blogoverviewpage_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='add_bottom_padding',
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlap_call_to_action',
            field=models.BooleanField(default=False, help_text='Display call to action above content.'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='overlap_call_to_action',
            field=models.BooleanField(default=False, help_text='Display call to action above content.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageBlock', [], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('fifty_fifty', 9), ('home_page_cover', 10), ('side_by_side', 11), ('full_screen_image_with_text_over', 16), ('product_comparison', 18)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Relative URL to page, e.g. /about-us/meet-the-team'}), 5: ('wagtail.blocks.StructBlock', [[('display_text', 3), ('path', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'max_num': 1, 'min_num': 0}), 7: ('wagtail.blocks.StructBlock', [[('show_button', 2)]], {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('aqua', 'Aqua'), ('black', 'Black'), ('charbrown', 'Charcoal Brown'), ('g2', 'Gen2'), ('g2blk', 'Gen2 Black'), ('racing', 'Racing'), ('seventycx', 'Seventy CX'), ('taskabackgroundgrey', 'TASKA Background Grey'), ('taskablack', 'TASKA Black'), ('taskablue', 'TASKA Blue'), ('taskacharcoal', 'TASKA Charcoal'), ('taskacoolgrey', 'TASKA Cool Grey'), ('taskadarkblue', 'TASKA Dark Blue'), ('taskagrey', 'TASKA Grey'), ('taskapink', 'TASKA Pink'), ('taskared', 'TASKA RED'), ('taskaultralightgrey', 'TASKA Ultralight Grey'), ('taskawheat', 'TASKA Wheat'), ('white', 'White')]}), 9: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('image_on_left', 2), ('button', 6), ('scroll_button', 7), ('bg_color', 8), ('text_color', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('button', 5)]], {}), 11: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('button', 5), ('scroll_button', 7), ('bg_color', 8), ('text_color', 8)]], {}), 12: ('wagtail.blocks.TextBlock', (), {'help_text': 'Text to display in a heading font.'}), 13: ('wagtail.blocks.TextBlock', (), {}), 14: ('wagtail.blocks.StructBlock', [[('title', 3), ('description', 13), ('image', 1), ('new', 2), ('button', 5), ('bg_color', 8)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('heading', 12), ('text', 0), ('image', 1), ('fade_image', 2), ('show_button', 2), ('text_on_left', 2), ('button', 5), ('cards', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (1,), {'max_num': 2}), 18: ('wagtail.blocks.StructBlock', [[('text', 0), ('images', 17), ('button', 5)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='content',
            field=wagtail.fields.StreamField([('page_title', 1), ('display', 4), ('staff_grid', 8), ('fifty_fifty', 15), ('side_by_side', 16), ('full_screen_image_with_text_over', 21), ('privacy_policy', 22), ('downloads', 32), ('overflow_card_list', 35), ('frequently_asked_questions', 39), ('select_display', 42)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.StructBlock', [[('columns', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 0), ('image', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('staff', 7)]], {}), 9: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Relative URL to page, e.g. /about-us/meet-the-team'}), 11: ('wagtail.blocks.StructBlock', [[('display_text', 0), ('path', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'max_num': 1, 'min_num': 0}), 13: ('wagtail.blocks.StructBlock', [[('show_button', 9)]], {}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('aqua', 'Aqua'), ('black', 'Black'), ('charbrown', 'Charcoal Brown'), ('g2', 'Gen2'), ('g2blk', 'Gen2 Black'), ('racing', 'Racing'), ('seventycx', 'Seventy CX'), ('taskabackgroundgrey', 'TASKA Background Grey'), ('taskablack', 'TASKA Black'), ('taskablue', 'TASKA Blue'), ('taskacharcoal', 'TASKA Charcoal'), ('taskacoolgrey', 'TASKA Cool Grey'), ('taskadarkblue', 'TASKA Dark Blue'), ('taskagrey', 'TASKA Grey'), ('taskapink', 'TASKA Pink'), ('taskared', 'TASKA RED'), ('taskaultralightgrey', 'TASKA Ultralight Grey'), ('taskawheat', 'TASKA Wheat'), ('white', 'White')]}), 15: ('wagtail.blocks.StructBlock', [[('text', 2), ('image', 5), ('image_on_left', 9), ('button', 12), ('scroll_button', 13), ('bg_color', 14), ('text_color', 14)]], {}), 16: ('wagtail.blocks.StructBlock', [[('text', 2), ('image', 5), ('button', 11), ('scroll_button', 13), ('bg_color', 14), ('text_color', 14)]], {}), 17: ('wagtail.blocks.TextBlock', (), {'help_text': 'Text to display in a heading font.'}), 18: ('wagtail.blocks.TextBlock', (), {}), 19: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 18), ('image', 5), ('new', 9), ('button', 11), ('bg_color', 14)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.StructBlock', [[('heading', 17), ('text', 2), ('image', 5), ('fade_image', 9), ('show_button', 9), ('text_on_left', 9), ('button', 11), ('cards', 20)]], {}), 22: ('wagtail.blocks.StructBlock', [[]], {}), 23: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('clinician', 'Clinicians'), ('user', 'Users')]}), 24: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 25: ('wagtail.blocks.StructBlock', [[('title', 0), ('category', 23), ('file', 24)]], {}), 26: ('wagtail.blocks.URLBlock', (), {}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('document', 'Document'), ('image', 'Image'), ('link', 'Link'), ('software', 'Software'), ('youtube', 'YouTube'), ('other', 'Other')]}), 28: ('wagtail.blocks.StructBlock', [[('title', 0), ('category', 23), ('file', 24), ('url', 26), ('file_type', 27)]], {}), 29: ('wagtail.blocks.StreamBlock', [[('file', 25), ('external_content', 28)]], {}), 30: ('wagtail.blocks.StructBlock', [[('title', 0), ('downloads', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {}), 32: ('wagtail.blocks.StructBlock', [[('categories', 31)]], {}), 33: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 18), ('image', 5), ('image_on_right', 9), ('image_pop_out', 9), ('bg_color', 14), ('text_color', 14)]], {}), 34: ('wagtail.blocks.ListBlock', (33,), {}), 35: ('wagtail.blocks.StructBlock', [[('title', 2), ('cards', 34), ('bg_color', 14), ('text_color', 14)]], {}), 36: ('wagtail.blocks.CharBlock', (), {'required': False}), 37: ('wagtail.blocks.StructBlock', [[('title', 36), ('text', 2)]], {}), 38: ('wagtail.blocks.ListBlock', (37,), {}), 39: ('wagtail.blocks.StructBlock', [[('title', 0), ('entries', 38)]], {}), 40: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 2)]], {}), 41: ('wagtail.blocks.ListBlock', (40,), {}), 42: ('wagtail.blocks.StructBlock', [[('title', 0), ('entries', 41)]], {})}, null=True),
        ),
    ]
